---
title: "2020-06-healthsites-paper-figs"
#output: html_document
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


# install.packages("remotes") # if not already installed
# remotes::install_github("afrimapr/afrihealthsites")

library(afrihealthsites)
library(knitr) #for kable
library(dplyr)
library(ggplot2)
library(patchwork)

```

```{r, eval=TRUE, include=FALSE}
#set to eval=TRUE to make figs for submission
# options to create final publication quality figures
# word doc summarises & figs get stored

# wellcome open research 
# https://wellcomeopenresearch.org/for-authors/article-guidelines/research-articles
# they want eps
# If none of the above options is possible then we also accept uncompressed TIFFs with a resolution of at least 600dpi at the size they are likely to be displayed at (see above).

opts_chunk$set(dev="tiff",
               #dev.args=list(compression="lzw"),
               dpi=600, #wellcome wants 600
               cache=FALSE,
               fig.path='2020-06-paper-figs/',
               fig.width=8.5,
               fig.height=10)
```


```{r, eval=FALSE, echo=FALSE, warning=FALSE}

#eval = FALSE because run already and takes few mins

  dfallcountries <- NULL

  #takes a few minutes to do all countries
  for( country in afcountries$name)
  {
    
    dfsumm <- merge_points(country, toreturn='summary', 
                           hs_amenity=c('clinic', 'doctors', 'pharmacy', 'hospital'),
                           dist_same_m = 50)
    
    dfallcountries <- rbind(dfallcountries, dfsumm)
  }

#reformatting dataframe

# rename columns containing num locations from first entry in source columns
names(dfallcountries)[which(names(dfallcountries)=='numpoints1')] <- as.character(dfallcountries$source1[1])
names(dfallcountries)[which(names(dfallcountries)=='numpoints2')] <- as.character(dfallcountries$source2[1])

# copy and rename object
df_hs_who_compare_50m <- dfallcountries

# remove source columns
df_hs_who_compare_50m <- df_hs_who_compare_50m[,-c(2,4)]

# save object
save(df_hs_who_compare_50m, file="data//df_hs_who_compare_50m.rda") 

```

```{r, echo=FALSE, asis=TRUE}

# load data created above

load("data//df_hs_who_compare_50m.rda")

```


Numbers by country in the three main datasets
(moh numbers hardcoded in based on Anelda's analysis)
TODO add code to count facilities from the data

```{r fig2_points_who_hs_moh, echo=FALSE, warnings=FALSE, asis=TRUE, fig.width=9, fig.height=9}

# arrange in order of who-kemri
df2 <- dplyr::arrange(df_hs_who_compare_50m, who, -healthsites)

positions <- df2$country

# pivot longer to structure data for plot
df3 <- tidyr::pivot_longer(df2, -c(country, threshdistm), names_to = "measure", values_to = "count")

# filter just rows wanted in plot
df4 <- dplyr::filter(df3,measure %in% c('healthsites','who'))

# ADD facility numbers from MoHs hardcoded for now
# TODO add code from Anelda to derive these from the data
dfmoh <- data.frame(country=c("Kenya","Malawi","Namibia","Rwanda","South Sudan","United Republic of Tanzania","Zambia"),
                    threshdistm=NA,
                    measure="moh",
                    count=c(12391,1546,589,1525,2889,10807,2828))

df5 <- rbind(df4,dfmoh)

# set factor order otherwise colours are wrong
df5$measure <- factor(df5$measure,levels=c("who", "healthsites","moh"))

# set colours
#point_cols <- c("who"='steelblue2', "healthsites"='firebrick1', "moh"='green3')
point_cols <- c('steelblue2', 'firebrick1','green3')

ggplot(df5, aes(x=country, y=count, colour=measure)) + 
  geom_point(alpha = 0.7) +
  scale_colour_manual(name="data source",
                    labels = c("WHO-KWTRP", "healthsites.io", "National List"),
                    values = point_cols) +
  #scale_shape_manual(values=c(1,1,2))+
  # labs(subtitle="Normalised mileage from 'mtcars'", 
  #      title= "Diverging Bars") +
  ylab("number of health facility locations") +
  scale_x_discrete(limits = positions) +
  #scale_y_log10() +
  theme_minimal() +
  coord_flip()

```



Compare per country distributions of facility types between who and healthsites 

```{r fig3_facility_types_hs_who9, echo=FALSE, warnings=FALSE, asis=TRUE, fig.width=9, fig.height=9}

country <- 'all'

# https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dclinic
# healthsites : clinic = > 10 doctors

hs_amenity <- c('clinic', 'doctors', 'pharmacy', 'hospital','dentist')

#WHO9 : I think I could cut it down further from 9
#also whocats9 from the table actually has 12 cats !
#whocats9
#  "Hospital" "Health Centre" "Health Post" "Maternity" "Community Health Unit"
#  "Dispensary" "Medical Center" "Health Clinic" NA  "Polyclinic"           
#  "Health Station"        "Health Hut" 
#should be:  hospital, health clinic, dispensary, community health unit, health post, health center, maternity ward, medical center, or polyclinic
sfwhoall <- afrihealthsites('all', datasource = 'who', plot=FALSE )
whocats9 <- unique(sfwhoall$facility_type_9)
whocatsless <- whocats9[which(! (whocats9=='Polyclinic' | whocats9=='Maternity' | whocats9=='Health station' ))]

#a check on the 240 NAs in reclassed WHO data
sfwhoNA <- sfwhoall[which(is.na(sfwhoall$facility_type_9)),]
#unique(sfwhoNA[['Facility type']]) # gives 17 types that appear not to have been converted
#"Unites de Santé de village"  "Postos Sanitários"           "Hospitais Regionais"         "Hospitais Centrais"
#"Centre Médico-Chirurgical"   "Centre Médico-Urbain"        "Poste De Santé"              "Clinic without Maternity"
#"Public Health Unit"          "Clinic with Maternity"       "Health post"                 "Area Health Centre"         
#"Family Health Clinic"        "Medi-Clinic"                 "Hospitais"                   "Postos de Saúde Comunitária"
#"Primary Health Care Unit +" 
#TODO add these into who_type_lookup

#type_filter <- whocatsless  

    gg1 <- afrihealthsites::facility_types(country,
                                    datasource = 'healthsites',
                                    plot_title = "A. healthsites.io",
                                    type_filter = hs_amenity,
                                    brewer_palette = "YlGn",
                                    plot=FALSE)
    
    # using consistent 9 class facility types for WHO data, specify type_column='facility_type_9'
    gg2 <- afrihealthsites::facility_types(country,
                                           datasource = 'who',
                                           plot_title = "B. WHO-KWTRP reclassified",
                                           type_filter = whocatsless,
                                           type_column = 'facility_type_9',
                                           brewer_palette = "BuPu",
                                           plot=FALSE)
    

      max_x1 <- max(ggplot_build(gg1)$layout$panel_params[[1]]$x$continuous_range)
      max_x2 <- max(ggplot_build(gg2)$layout$panel_params[[1]]$x$continuous_range)
      #set xmax for both plots to this
      gg1 <- gg1 + xlim(c(0,max(max_x1,max_x2, na.rm=TRUE)))
      gg2 <- gg2 + xlim(c(0,max(max_x1,max_x2, na.rm=TRUE)))

      #set size of y plots to be dependent on num cats
      #y axis has cats, this actually gets max of y axis, e.g. for 6 cats is 6.6
      max_y1 <- max(ggplot_build(gg1)$layout$panel_params[[1]]$y$continuous_range)
      max_y2 <- max(ggplot_build(gg2)$layout$panel_params[[1]]$y$continuous_range)

      #setting heights to num cats makes bar widths constant between cats
      gg1 / gg2 + plot_layout(heights=c(max_y1, max_y2)) #patchwork    

```

```{r hs_beds_doctors, echo=FALSE, warnings=FALSE, asis=TRUE, fig.width=9, fig.height=9}

# try to count the numbers of attribute entries in healthsites data
country <- 'all'

sfhsall <- afrihealthsites(country, datasource = 'healthsites', plot=FALSE)

ids_beds <- which((sfhsall$beds != "")) #469
ids_docs <- which((sfhsall$staff_doctors != "")) #890
ids_nurs <- which((sfhsall$staff_nurses != "")) #934

934/56854 #1.64%

```

```{r fig8_zambia_moh, eval=FALSE, echo=FALSE, warnings=FALSE, asis=TRUE, fig.width=9, fig.height=9}

#eval=FALSE because this has developed an error. a zoomed screenshot is used for the paper anyway
#it is due to passing the df or sf to compare_hs_sources()
# Error in if (!is.na(getProjection(lst[[i]]))) { : 
#   argument is of length zero 

url_zambia <- "https://raw.githubusercontent.com/MOH-Zambia/MFL/master/geography/data/facility_list.csv"

#problem with data that there are some NAs in coords columns 
#this fixes it
dfzambia <- read.csv(url_zambia)
dfzambia <- dfzambia[-which(is.na(dfzambia$longitude)),]

#plot zambia map on its own
sfzambia <- afrihealthsites('zambia',
                            datasource = dfzambia,
                            type_column = 'facility_type',
                            label_column = 'name',
                            lonlat_columns = c("longitude", "latitude"),
                            plot=FALSE)

#comparison of zambia data with that in who-KWTRP
#datasources <- list('who', dfzambia)
datasources <- list('who', sfzambia)

compare_hs_sources('zambia', datasources=datasources, type_column = 'facility_type', label_column = 'name', lonlat_columns = c("longitude", "latitude"))

#nice comparison between MFL and WHO - similar, extra types in MFL 
#but bit complicated to compare for the paper
#facility_types('zambia',datasource=dfzambia,type_column='facility_type',label_column='name',lonlat_columns = NULL)
#facility_types('zambia',datasource='who')


```
