---
title: "compare_moh_tanzania"
output: html_document
---

To compare moh data from Tanzania downloaded now with Kemri collated data from 2019.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(afrihealthsites)
library(knitr) #for kable
library(dplyr)
library(ggplot2)

```


```{r, eval=TRUE, warning=FALSE}

tanzania_file <- "data-raw\\health-facilities-moh-tanzania.csv"

# test reading in file
#tst <- read.csv(tanzania_file, as.is=TRUE, check.names=FALSE)

```


```{r map_moh_tanzania, eval=FALSE, warning=FALSE}

# 9378 obs

# just view MoH data
sfmoh_tza <- afrihealthsites("Tanzania", datasource=tanzania_file,
                             type_column = 'Facility Type',
                             label_column = 'Facility Name',
                             lonlat_columns = c("Longitude", "Latitude"))

#testing filter
#sfmoh_tza <- afrihealthsites("Tanzania", datasource=tanzania_file, type_filter='Dispensary')
#filter with two types
#sfmoh_tza <- afrihealthsites("Tanzania", datasource=tanzania_file, type_filter=c('Dispensary','Health Center'))

#trying to remove one from selection doesn't work
#sfmoh_tza <- afrihealthsites("Tanzania", datasource=tanzania_file, type_filter='-Dispensary')
#sfmoh_tza <- afrihealthsites("Tanzania", datasource=tanzania_file, type_filter='!Dispensary')

# plot moh vs kemri on a map
# this does work now but only because the defaults are set up for Tanzania
# todo sort code so will work for other countries
compare_hs_sources("Tanzania", datasources=c('who',tanzania_file),
                   type_column = 'Facility Type',
                   label_column = 'Facility Name')
                   #lonlat_columns = c("Longitude", "Latitude"))

# most overlap but not total

# moh data excludes zanzibar
# I added zanzibar into tanzania for kemri data

# todo 
# remove zanzibar from who for the comparison
# compare moh & who data, e.g. number locations of different categories


```

Plot counts of facility types from MoH data
```{r compare_type_frequencies, echo=FALSE, warnings=FALSE, asis=TRUE, fig.width=9, fig.height=9}

#
ggtza <- facility_types("tanzania", 
                        datasource=tanzania_file,
                        type_column = "Facility Type",
                        lonlat_columns = c("Longitude", "Latitude"))
plot(ggtza)


#with filter
ggtza <- facility_types("tanzania", 
                        datasource=tanzania_file,
                        type_column = "Facility Type",
                        type_filter=c('Dispensary','Health Center'),
                        lonlat_columns = c("Longitude", "Latitude"))
plot(ggtza)

#TODO allow negative filter, e.g. to exclude dispensary

```


