---
title: "compare_moh_kenya"
output: html_document
---

To compare moh data from kenya downloaded 2021 with Kemri collated data from 2019.

Kenya MFL MoH download does not have coordinates.
Data from Caroline 2021-04 does have coordinates.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(afrihealthsites)
library(knitr) #for kable
library(dplyr)
library(ggplot2)
library(sf) #to read in shapefile

```


Data from WiGISKe 2021-4 seem to be the best data.

```{r read-wigiske, eval=TRUE, warning=FALSE, echo=FALSE}

wigiske_file <- "data-raw\\health-facilities-kenya-2021-04\\Healthcare_Facilities.shp"

# test reading in file
sfken <- sf::st_read(wigiske_file)

names(sfken)
# [1] "OBJECTID"   "Facility_N" "Type"       "Owner"      "County"     "Sub_County" "Division"   "Location"  
# [9] "Sub_Locati" "Constituen" "Nearest_To" "Latitude"   "Longitude"  "geometry"  

length(names(sfken))
#14

#26 types
fac_types_wigiske <- unique(sfken[['Type']])
#22 owners
owners_wigiske <- unique(sfken[['Owner']])


nrow(sfken)
# 10013



```



```{r read-moh, eval=TRUE, warning=FALSE, echo=FALSE}

kenya_file <- "data-raw\\health-facilities-moh-kenya.csv"

# test reading in file
dfken <- read.csv(kenya_file, as.is=TRUE, check.names=FALSE)

names(dfken)
#  [1] "Code"                   "Name"                   "Officialname"           "Registration_number"   
#  [5] "Keph level"             "Facility type"          "Facility_type_category" "Owner"                 
#  [9] "Owner type"             "Regulatory body"        "Beds"                   "Cots"                  
# [13] "County"                 "Constituency"           "Sub county"             "Ward"                  
# [17] "Operation status"       "Open_whole_day"         "Open_public_holidays"   "Open_weekends"         
# [21] "Open_late_night"        "Service_names"          "Approved"               "Public visible"        
# [25] "Closed" 

#length(names(dfken))
#25

#29 cats
fac_types_moh <- unique(dfken[['Facility type']])
#9 cats
fac_type_cats_moh <- unique(dfken[['Facility_type_category']])
#19 owners
owners_moh <- unique(dfken[['Owner']])

nrow(dfken)
# 12378

```


```{r map_moh_kenya, eval=FALSE, warning=FALSE}

#eval=FALSE because no coordinates

# just view MoH data
sfmoh_ken <- afrihealthsites("kenya", datasource=kenya_file,
                             type_column = 'Facility_type_category',
                             label_column = 'Facility Name',
                             lonlat_columns = c("Longitude", "Latitude"))

#testing filter
#sfmoh_ken <- afrihealthsites("kenya", datasource=kenya_file, type_filter='Dispensary')
#filter with two types
#sfmoh_ken <- afrihealthsites("kenya", datasource=kenya_file, type_filter=c('Dispensary','Health Center'))

#trying to remove one from selection doesn't work
#sfmoh_ken <- afrihealthsites("kenya", datasource=kenya_file, type_filter='-Dispensary')
#sfmoh_ken <- afrihealthsites("kenya", datasource=kenya_file, type_filter='!Dispensary')

# plot moh vs kemri on a map
# this does work now but only because the defaults are set up for kenya
# todo sort code so will work for other countries
compare_hs_sources("kenya", datasources=c('who',kenya_file),
                   type_column = 'Facility Type',
                   label_column = 'Facility Name')
                   #lonlat_columns = c("Longitude", "Latitude"))




```

Plot counts of facility types from MoH data
```{r ken_moh_facility_types, echo=FALSE, warning=FALSE, asis=TRUE, fig.width=8, fig.height=8}

# Facility_type_category
ggken <- facility_types("kenya", 
                        datasource=kenya_file,
                        type_column = 'Facility_type_category',
                        lonlat_columns = NULL) #specifying that there are no coords
plot(ggken)

# Keph level, defined facility levels
ggken <- facility_types("kenya", 
                        datasource=kenya_file,
                        type_column = "Keph level",
                        lonlat_columns = NULL) #specifying that there are no coords
plot(ggken)

# Owner type = public/private
ggken <- facility_types("kenya", 
                        datasource=kenya_file,
                        type_column = "Owner type",
                        lonlat_columns = NULL) #specifying that there are no coords
plot(ggken)

as.data.frame(table(dfken$`Owner type`))
# 1       Faith Based Organization 1035
# 2             Ministry of Health 5875
# 3 Non-Governmental Organizations  366
# 4               Private Practice 5102


#number of beds - but the default plot doesn't cope well with the numeric data
ggken <- facility_types("kenya", 
                        datasource=kenya_file,
                        type_column = 'Beds',
                        lonlat_columns = NULL) #specifying that there are no coords
plot(ggken)



```


#Note that the MOH file doesn't have coordinates
#but it does have sub-county (?admin3)


