---
title: "compare_moh_south_sudan"
output: html_document
---

To compare moh data from South Sudan downloaded now with Kemri collated data from 2019.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(afrihealthsites)
library(knitr) #for kable
library(dplyr)
library(ggplot2)

```


```{r, eval=FALSE, warning=FALSE}

ssudan_file <- "data-raw\\south_sudan_facility_info_2020-05-13.csv"

# test reading in file
dfssd <- read.csv(ssudan_file, as.is=TRUE, check.names=FALSE)


#ssudan has a single location column containing coords divided by commas as strings 
# fair few coords at null island 0,0
# seemingly some NAs, or maybe problem with me trying to pass single Location rather than 2 columns
#which(is.na(dfssudan$Location))
#sfssudan <- sf::st_as_sf(dfssudan, coords='Location')

#dfs <- head(dfssudan)

#divide into 2 columns
dfcoords <- as.data.frame(stringr::str_split(dfssd$Location,", ",simplify=TRUE), stringsAsFactors = FALSE)
#change to numeric
dfcoords <- lapply(dfcoords,as.numeric)
#name columns
#names(dfcoords) <- c("Longitude", "Latitude")
names(dfcoords) <- c("Latitude", "Longitude")
#bind back onto df
dfssd <- cbind(dfssd, dfcoords)

sfssd <- sf::st_as_sf(dfssd, coords=c("Longitude", "Latitude"), crs = 4326)

mapview::mapview(sfssd)

#save
save(sfssd, file="sfssd.rda")

```


```{r map_moh_ssudan, eval=FALSE, warning=FALSE}

# 9378 obs

# just view MoH data
sfmoh <- afrihealthsites("South Sudan", datasource=ssudan_file, lonlat_columns = "Location")

# try passing just pre-read sf object 
sfmoh <- afrihealthsites("South Sudan", datasource=sfssd,                              
                         type_column = 'type',
                         label_column = 'Facility')

#testing filter
#sfmoh_tza <- afrihealthsites("Tanzania", datasource=tanzania_file, type_filter='Dispensary')
#filter with two types
#sfmoh_tza <- afrihealthsites("Tanzania", datasource=tanzania_file, type_filter=c('Dispensary','Health Center'))

#trying to remove one from selection doesn't work
#sfmoh_tza <- afrihealthsites("Tanzania", datasource=tanzania_file, type_filter='-Dispensary')
#sfmoh_tza <- afrihealthsites("Tanzania", datasource=tanzania_file, type_filter='!Dispensary')

# plot moh vs kemri on a map
compare_hs_sources("south sudan", datasources=c('who',ssudan_file))

# most overlap but not total

# moh data excludes zanzibar
# I added zanzibar into tanzania for kemri data

# todo 
# remove zanzibar from who for the comparison
# compare moh & who data, e.g. number locations of different categories


```

Plot counts of facility types from MoH data
```{r compare_type_frequencies, echo=FALSE, warnings=FALSE, asis=TRUE, fig.width=9, fig.height=9}

# trying to pass the sf object directly
ggssd <- facility_types("south sudan", 
                        datasource=sfssd,
                        type_column = "type")
plot(ggssd)



```


