---
title: "dhs_spa_explore"
#output: html_document
output: word_document
---

Exploring data from DHS Service Provision Assessment (SPA).
Andy South

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rdhs)
library(afrihealthsites)
#library(dplyr)

#set my dhs ID - it will then ask for passwd : B

set_rdhs_config(email = "andy.south@lstmed.ac.uk",
                project = "afrimapr : creating R building-blocks to ease use of open health data in Africa",
                config_path = "rdhs.json",
                global = FALSE)


```

```{r malawi_spa_2013, eval=FALSE, echo=FALSE, asis=TRUE}

# from Web seems there is a Malawi SPA from 2013 :
# https://dhsprogram.com/data/dataset/Malawi_SPA_2013.cfm?flag=0
# seems that this doesn't appear in the query from rdhs
# webpage indicates 977 facilities surveyed
# this is apparently the geographic data (.shp) from the 2013-14 SPA
# MWGE6IFLSR.ZIP

#from here suggestion download from the ID: https://github.com/ropensci/rdhs/issues/74

#trying to repeat for the Malawi 2013-14 SPA survey
g <- get_datasets("MWGE6IFLSR.ZIP")
r <- readRDS(g$MWGE6IFLSR)
head(r@data,0)

# These requested datasets are not available from your DHS login credentials:
# MWGE6IFLSR.ZIP
# Please request permission for these datasets from the DHS website to be able to download them

# TODO is the issue that I didn't request shapefiles permission from DHS ?

#try this instead
#fileType='FC' for Facility
datasets <- dhs_datasets(countryIds = c("MW"), surveyYearStart = 2013, surveyType='SPA', fileType = 'FC', fileFormat = 'Flat')

#produces 2 rows that look mostly same

# download datasets
downloads <- get_datasets(datasets$FileName)

# Downloading: 
# Malawi 2013 SPA Facility Flat ASCII data (.dat) [MWFC6JFLSR.ZIP]
# Dataset download finished
# Downloading: 
# Malawi 2013 SPA Facility Flat ASCII data (.dat) [MWFC6KFLSP.ZIP]
# Dataset download finished

spamw <- readRDS(downloads[1])
#Error in readRDS(downloads[1]) : bad 'file' argument

#seems to be problem with the file string created by rdhs

downloads[1]
#$MWFC6JFLSR
#[1] "C:\\Users\\ANDY~1.SOU\\AppData\\Local/Andy.South/rdhs/Cache/datasets/MWFC6JFLSR.rds"

#file.exists(downloads[1])
#Error in file.exists(downloads[1]) : invalid 'file' argument

path <- "C:\\Users\\andy.south\\AppData\\Local\\Andy.South\\rdhs\\Cache\\datasets\\"
filename <- "MWFC6JFLSR.rds"

filename <- paste0(path, filename)

spamw <- readRDS(filename)

#cool does read in now

#has columns for facility ids, facility type & services
#column names are codes, with labels that are more informative
#seemingly not lat longs

#the files are different, same num rows so prob for same facilities
filename2 <- "MWFC6KFLSP.rds"
filename2 <- paste0(path, filename2)
spamw2 <- readRDS(filename2)

# try looking at this for getting shapefiles

# Here is rdhs vignette on downloading shapefiles (but seems to be boundaries) :
# https://cran.r-project.org/web/packages/rdhs/vignettes/boundaries.html

# datasets$SurveyId
# [1] "MW2013SPA" "MW2013SPA"

#this fails to download anything
#sfb <- download_boundaries(surveyId = "MW2013SPA", method = "sf")



```


```{r first_explore, eval=FALSE, echo=FALSE, asis=TRUE}

survey_characteristics <- dhs_survey_characteristics()


## find all the surveys that match the search criteria
#surveys <- dhs_surveys(countryIds = c("SN"), surveyYearStart = 2018)

#need to use dhs_datasets to get at SPA data

datasets <- dhs_datasets(countryIds = c("SN"), surveyYearStart = 2017, surveyType='SPA', fileFormat = 'Flat')
datasets$FileType
# [1] "Facility"               "Family Planning"        "Provider"               "Sick Child"            
# [5] "Staff/Provider Listing"

#fileType='FC' for Facility
datasets <- dhs_datasets(countryIds = c("SN"), surveyYearStart = 2017, surveyType='SPA', fileType = 'FC', fileFormat = 'Flat')
datasets <- dhs_datasets(countryIds = c("SN"), surveyYearStart = 2017, surveyType='SPA', fileType = 'FC', fileFormat = 'Hierarchical')

# download datasets
downloads <- get_datasets(datasets$FileName)

# Some of your available datasets are not found in the DHS API.This is likely due to the DHS API being out of date and as such some of the meta information about your available datasets may not be available.
# Downloading: 
# Senegal 2017 SPA Facility Flat ASCII data (.dat) [SNFC7ZFLSP.ZIP]
# Dataset download finished

spa_sn2017 <- readRDS(downloads[1])

str(spa_sn2017)

#794 rows, 1782 columns
#facil #facility identification, starting 50001

#Aha 2018 data is visible now - but download fails
datasets <- dhs_datasets(countryIds = c("SN"), surveyYear = 2018, surveyType='SPA', fileType = 'FC')
# but gives this error when trying to download
downloads <- get_datasets(datasets$FileName)
# Downloading: NA NA NA NA NA [NA]
# Error in if (file.size(tf) != desired_dataset$FileSize[1] & attempts ==  : 
#   missing value where TRUE/FALSE needed
datasets$FileName
#[1] "SNFC8HDTSP.ZIP" "SNFC8HFLSP.ZIP" "SNFC8HSDSP.ZIP" "SNFC8HSVSP.ZIP"

# try 2017 again - worked for all 4 file formats
datasets <- dhs_datasets(countryIds = c("SN"), surveyYear = 2017, surveyType='SPA', fileType = 'FC')
downloads <- get_datasets(datasets$FileName)

sn2017stata <- readRDS(downloads[1])

#https://www.measureevaluation.org/resources/publications/ms-14-88


#TODO
# ~ check this against the downloaded file
# ~ check again on 2018 data that is sposed to be there


```


