---
title: "drc-health-zones"
output: html_document
---
  
Look at health zone data from red cross on HDX  

https://data.humdata.org/dataset/drc-health-data

Note there are some seemingly older health zones data on HDX too.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)

#library(tidyverse)
library(dplyr)
library(ggplot2)
library(readr)
library(purrr) # for pluck
library(sf)
library(tmap)
library(lubridate)
library(afriadmin)
library(raster)


#using new path specification avoiding double slashes
#folder <- r"(C:\Dropbox\_afrimapr\data\covid-hera-hdx\)"

```


```{r, drc-zones-rhdx, eval=TRUE, warning=FALSE}

library(rhdx)

set_rhdx_config(hdx_site = "prod")
get_rhdx_config()

#1st dataset returned is the red cross one I want
#1st resource is areas - 5849
#2nd resource is zones - 519

ds1 <- search_datasets("drc-health-data") %>% 
  pluck(1) #%>% ## select the first dataset
  
sfareas <- ds1 %>% 
           get_resource(1) %>%  
           read_resource()

sfzones <- ds1 %>% 
           get_resource(2) %>%  
           read_resource()

# also there are red cross centre locations
# Title: DRC Red Cross Health Center Locations
# Name: drc_red-cross-health-data
# Date: [2018-11-21T00:00:00
  
mapview::mapview(sfareas, zcol='edite_par', label=paste(sfareas$AS,"in",sfareas$ZS))

mapview::mapview(sfzones, zcol='SCE_GEO')

```

```{r, drc-grid3-healthcatchments, eval=TRUE, warning=FALSE}

ds <- search_datasets("drc grid3 catchments") %>% 
  pluck(1) #%>% ## select the first dataset
  
ds %>% get_resources() 
#1st resource is pdf, 2nd is zip containing shape, but rhdx fails to open
#i think because zip also contains pdf & gdb
#Error in CPL_get_layers(dsn, options, do_count) : Open failed.
#so instead I downloaded and saved

# sfg3catch <- ds %>% 
#            get_resource(2) %>%  
#            read_resource()

#fails with gdal error when try to read from github because it just downloads 1 file and can't find the shx
#urlfolder <- "https://raw.githubusercontent.com/afrimapr/afrimapr_dev/master/data-raw/grid3-drc/"
urlfolder <- "data-raw/grid3-drc/"

#GRID3_DRC_HL_TN_Health_Zones_V01_Beta

#27 zones
sfg3zones <- sf::st_read(paste0(urlfolder,"GRID3_DRC_HL_TN_Health_Zones_V01_Beta.shp"))
#589 areas
sfg3areas <- sf::st_read(paste0(urlfolder,"GRID3_DRC_HL_TN_Health_Areas_V01_Beta.shp"))

mapview::mapview(sfg3areas, zcol='source', label=paste(sfg3areas$aire_sante,"in",sfg3areas$zone_sante))

```

```{r, drc-grid3-facilities, eval=TRUE, warning=FALSE}

ds <- search_datasets("drc grid3 facilities") %>% 
  pluck(1) #%>% ## select the first dataset
  
ds %>% get_resources() 

#1st resource is pdf, 2nd is zip containing shape

#again downloaded because the zip fails rhdx

# 1395 facilities
sfg3facilities <- sf::st_read(paste0(urlfolder,"GRID3_DRC_HL_TN_Health_Facilities_V01_Beta.shp"))



```


```{r, drc-grid3-catchment-wpop, eval=TRUE, warning=FALSE}

#try worldpop to get over 60 popn per health catchment

# using older worldpop data on age profiles for all of DRC
# they are available as one tiff file per age/sex group
# https://www.worldpop.org/geodata/summary?id=50153
# and via package wpgpDownloadR

#file created in worldpop-ages.Rmd using package wpgpDownloadR

datapath <- "C:\\Dropbox\\_afrimapr\\data\\worldpop\\cod_60to80.tif"

rast6080 <- raster::raster(datapath)

#aggregate from 100m to 1km to see if works better for display
#sum to get total popn counts
rast6080_1km <- raster::aggregate(rast6080, fun=sum, fact=10)
#maximum number of pixels for Raster* viewing is 5e+05 ; the supplied Raster* has 5182212
#dim(rast6080_1km) # 2261 2292 max value 4k
rast6080_4km2 <- raster::aggregate(rast6080, fun=sum, fact=20)
rast6080_10km <- raster::aggregate(rast6080, fun=sum, fact=100)


#https://geocompr.robinlovelace.net/geometric-operations.html#raster-extraction

#takes many minutes to complete
dfg3areas6080 <- raster::extract(x = rast6080, y = sfg3areas, df = TRUE) 
#eek 20 million rows

#ID column contains the row number of the polygon
#The order of the returned values corresponds to the order of object y. If df=TRUE, this is also indicated in the first variable ('ID').

df6080bypoly <-dfg3areas6080 %>%
  group_by(ID) %>%
  summarise(numover60s = as.integer(sum(cod_60to80, na.rm=TRUE)),
            density = mean(cod_60to80, na.rm=TRUE), 
            ncells = n())

#can just rbind the results back onto the sf object
sfg3area6080 <- cbind(sfg3areas, df6080bypoly)

#this is good test showing that high value polygons do correspond to high raster values
mapview(sfg3area6080, zcol='numover60s') +
  mapview(rast6080_10km, at = c(0,1,10,100,1000,10000,105000))

#TODO check why raster at 10x10km has a max of 100,000
#but polygons have a max of ~ 5,000 even though they seem to be bigger than the raster cells ?


mapview::mapview(rast6080)

mapview::mapview(rast6080_10km) #max 105,000

#list sequential palettes avail in mapview
hcl.pals("sequential")

breaks <- c(0,1,10,100,1000,10000,105000)
palname <- 'Purples 3'
palname <- "Turku"
palname <- "SunsetDark"
palname <- "Oslo"
palname <- "Lajolla"
mapview(rast6080_10km, col.regions=hcl.colors(n=length(breaks)-1, palette=palname, rev=FALSE), at=breaks )

#saving zone polygons as lines to make vis easier in app
sfg3zonelines <- sf::st_cast(sfg3zones,"MULTILINESTRING")

#save R objects to use in app
save(rast6080_10km, file="drc_prototype_app//cod_rast6080_10km.rda")
save(sfg3area6080, file="drc_prototype_app//sfg3area6080.rda")
save(sfg3zones, file="drc_prototype_app//sfg3zones.rda")
save(sfg3facilities, file="drc_prototype_app//sfg3facilities.rda")
save(sfg3zonelines, file="drc_prototype_app//sfg3zonelines.rda")

# to be able to use here without needing to recreate
load("drc_prototype_app//sfg3area6080.rda")
load("drc_prototype_app//sfg3zones.rda")
load("drc_prototype_app//sfg3zonelines.rda")
load("drc_prototype_app//sfg3facilities.rda")

# reduce size of areas file to try to make shinyapps faster
library(rmapshaper)

sfg3area6080keep5 <- ms_simplify(sfg3area6080, keep = 0.05)
sfg3zonelineskeep5 <- ms_simplify(sfg3zonelines, keep = 0.05)

save(sfg3area6080keep5, file="drc_prototype_app//sfg3area6080keep5.rda")
save(sfg3zonelineskeep5, file="drc_prototype_app//sfg3zonelineskeep5.rda")


```


```{r, drc-grid3-wopr-fails, eval=FALSE, warning=FALSE}

# FAILS because the wopr data for DRC are for a few provinces around Kinshasa, not where the health catchment area data are

#remotes::install_github('wpgp/wopr')
library(wopr)

# checking what DRC data is in the worldpop catalog
catalogue <- getCatalogue()
#catalogue <- getCatalogue(spatial_query=T) #suggests that v1.0 & v2.0 accept spatial queries

# Select files from the catalogue by subsetting the data frame
selection <- subset(catalogue,
                    country == 'COD' &
                    category == 'Population')


#andy to get over 60s 
sexes <- c("m", "f")
ages <- seq(60, 80, 5)
over60 <- c(paste0(rep(sexes,each=length(ages)),ages))

#both areas & zones fail

#Submitting 589 feature(s) to:  https://api.worldpop.org/v1/wopr/polyagesex 
#Checking status of 605 tasks:
#  11%...22%...33%...44%...55%...Error in results[[j]] : subscript out of bounds

# Submitting 27 feature(s) to:
#   https://api.worldpop.org/v1/wopr/polyagesex 
# Checking status of 42 tasks:
#   12%...24%...Error in results[[j]] : subscript out of bounds

# get population totals
#589 areas
sfg3areaswpop60 <- woprize(features=sfg3areas,
                  country='COD',
                  version='v2.0',
                  #my age selction >=60
                  agesex_select=over60,
                  confidence=0.95,
                  tails=2,
                  belowthresh=1e5,
                  abovethresh=2e5
                  )
#27 zones
sfg3zoneswpop60 <- woprize(features=sfg3zones,
                  country='COD',
                  #version='v1.2',
                  #my age selction >=60
                  agesex_select=over60,
                  confidence=0.95,
                  tails=2,
                  belowthresh=1e5,
                  abovethresh=2e5
                  )

#just one zone does work and returns results nearly straightaway
#but NA for all numeric results and MESSAGE column says 'Internal File Error'
#even doing for first 10 rows gives NAs and Internal File Error in all
#setting version-'v2.0' fixed it to return non NA values
#but now has zeroes for all in mean, median & belowthresh =1
#also v1.0 gives zeros too
sfg3zoneswpop60 <- woprize(features=sfg3zones[1:10,],
                  country='COD',
                  version='v1.0'#,
                  #my age selction >=60
                  #agesex_select=over60,
                  #confidence=0.95,
                  #tails=2,
                  #belowthresh=1e5,
                  #abovethresh=2e5
                  )

```




```{r, drc-redcross-centres, eval=TRUE, warning=FALSE}

# 22 red cross centre locations
# Title: DRC Red Cross Health Center Locations
# Name: drc_red-cross-health-data
# Date: [2018-11-21T00:00:00

ds <- search_datasets("drc_red-cross-health-data") %>% 
  pluck(1) #%>% ## select the first dataset
 
ds %>% get_resources() 

sf_rc_centres <- ds %>% 
           get_resource(1) %>%  
           read_resource()
  
#mapview::mapview(sf_rc_centres)

```

