---
title: "Senegal HOT microgrant analyses"
#output: html_document
author: "Andy South @afrimapr"
date: "`r Sys.Date()`"
output: pdf_document
#output: word_document
---

#TO OUTPUT HIGH QUALITY TIFFS set to word above & eval=TRUE the 2nd chunk


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)

library(afrihealthsites)
library(knitr) #for kable
library(dplyr)
library(ggplot2)

```

```{r, eval=FALSE, include=FALSE}
# set to eval=TRUE to make figs for submission
# in YAML set output: word_document
# word doc summarises & figs get stored in folder

opts_chunk$set(dev="tiff",
               #dev.args=list(compression="lzw"),
               dpi=300, 
               cache=FALSE,
               fig.path='2021-02-senegal-plots/',
               fig.width=8.5,
               fig.height=10)
```


To compare newly collected data on Senegal health facility locations with that from healthsites.io, WHO. 
Part of HOT microgrant.
November 2020


```{r read-data, eval=TRUE}


sfsen_who <- afrihealthsites::afrihealthsites('senegal', datasource = 'who', plot = FALSE)

#dfsen_who <- afrihealthsites::afrihealthsites('senegal', datasource = 'who', plot = FALSE, returnclass = 'dataframe')

sfsen_hs <- afrihealthsites::afrihealthsites('senegal', datasource = 'healthsites', plot = FALSE)
# remove pharmacies, dentists & NA
#sfsen_hs <- filter(sfsen_hs, amenity != "pharmacy")
sfsen_hs <- filter(sfsen_hs, amenity %in% c("clinic","doctors","hospital"))
# convert beds to numeric
sfsen_hs$beds <- as.numeric(sfsen_hs$beds) 

#2020-11-Senegal-emergency-health-data_update-osm.xlsx

urldata <- "https://raw.githubusercontent.com/afrimapr/afrimapr_dev/master/data-raw/2020-11-Senegal-emergency-health-data_update-osm.csv"

# read in data
# first versions saved from googlesheets needed to be read in utf8
dfsen_sur <- read.csv(urldata, encoding = 'UTF-8', check.names = FALSE)

#dfuser <- googlesheets4::read_sheet(ss = urldata)
# convert to spatial format
sfsen_sur <- sf::st_as_sf(dfsen_sur, coords = c("longitude", "latitude"), crs = 4326, na.fail=FALSE)
# remove 1 pharmacy from survey data to make map legends clearer
sfsen_sur <- filter(sfsen_sur, building != "Pharmacy")


#mapview::mapview(sfsen_sur, zcol='building')

# Warning message: In do.call(paste, args) :
#   unable to translate '<U+FEFF>name' to native encoding
#TODO fix name of first column

#str(sfsen_sur)
 # $ <U+FEFF>name        : chr  "Centre de santé de Rufisque" 
 # $ building            : chr  "Doctors" "Doctors" "Hospital" "Doctors" ...
 # $ addr:full           : chr  "Rue Savers" 
 # $ contact:phone       : num  2.21e+11 NA 2.21e+11 NA NA ...
 # $ operator            : chr  "État du Senegal" 
 # $ operator:type       : chr  "Public" "Public" "Government" "" ...
 # $ operational_status  : chr  "Operational" "Operational" 
 # $ opening_hours       : chr  "24/7 - All day, every day" 
 # $ wheelchair          : chr  "Yes" "Yes" "Yes" "Yes" ...
 # $ health_amenity:type : chr  "Doctor Pharmacy Dentist Laboratory Optometry/Ophtalmology Birthing center" "Doctor Pharmacy Laboratory Rehabilitation Birthing center" "Pharmacy Clinic Alternative Laboratory" "Doctor Pharmacy Dentist Laboratory Birthing center" ...
 # $ healthcare:equipment: chr  "Ultrasound X-Ray Operating Theater Laboratory Imaging Equipment Emergency Department" "Ultrasound X-Ray Laboratory Imaging Equipment Emergency Department" "MRI Laboratory Imaging Equipment Emergency Department" "Laboratory" ...
 # $ emergency           : chr  "Yes" "Yes" "Yes" "No" ...
 # $ insurance:health    : chr  "Public Private" "Public Private" "Private" ...
 # $ staff_count:doctors : int  4 8 4 2 NA 30 NA 2 NA 9 ...
 # $ staff_count:nurses  : int  10 7 22 2 NA 10 NA 3 NA 4 ...
 # $ beds                : int  40 44 16 15 NA 15 NA NA NA 10 ...
 # $ electricity         : chr  "Power grid" "Power grid" "Power grid" "Power grid" ...
 # $ water_source        : chr  "Water works" "Water works" "Water works" "Water works" ...



```

\pagebreak
Number of beds per facility in survey data and before.

```{r survey2020-beds, eval=TRUE, fig.height=4.5, fig.width=7.5, fig.show='hold'}

library(tmap)
library(afriadmin)

sfsen_adm0 <- afriadmin('senegal',level=0, plot=FALSE)

#zoom in ?
#log size scale to show smaller num beds

tmap::tm_shape(sfsen_adm0) +
    tm_borders("black", lwd = .5) +
    #tm_text("iso_a3", size = "AREA") +
#add NA points, have to do separately because shapeNA doesn't work for size    
tm_shape(sfsen_sur[is.na(sfsen_sur$beds),]) +
  tm_dots(shape=3, size = 0.15, col='grey', border.lwd = 0.2) +    
tm_shape(sfsen_sur) +
    tm_symbols(col = "building", alpha=0.8, size = "beds", size.max=420, 
               scale=3, sizes.legend=c(10,100,400), title.col="") +
tm_add_legend(type="symbol", shape=3, labels = "no bed data", size = 0.5, border.lwd = 0.5, col = "grey") +
    tm_scale_bar(breaks=c(0,50,100), position=c("LEFT", "BOTTOM")) +
    tm_layout(main.title='Bed data collected 2020', main.title.size=1,
              legend.bg.color=TRUE,
              title="map by @afrimapr", title.color="darkgrey", title.size=0.8, title.position=c("RIGHT","BOTTOM")) #main.title goes above map

```


```{r osmb4-beds, eval=TRUE, fig.height=4.5, fig.width=7.5, fig.show='hold'}

# healthsites data before
tmap::tm_shape(sfsen_adm0) +
    tm_borders("black", lwd = .5) +
    #tm_text("iso_a3", size = "AREA") +
#add NA points, have to do separately because shapeNA doesn't work for size    
tm_shape(sfsen_hs[is.na(sfsen_hs$beds),]) +
  tm_dots(shape=3, size = 0.15, col='grey', border.lwd = 0.2) +    
tm_shape(sfsen_hs) +
    tm_symbols(col = "amenity", alpha=0.8, size = "beds", size.max=420, 
               scale=3, sizes.legend=c(10,100,400), title.col="") +
tm_add_legend(type="symbol", shape=3, labels = "no bed data", size = 0.5, border.lwd = 0.5, col = "grey") +
    tm_scale_bar(breaks=c(0,50,100), position=c("LEFT", "BOTTOM")) +
    tm_layout(main.title='Bed data in OSM before 2020', main.title.size=1,
              legend.bg.color=TRUE,
              title="map by @afrimapr", title.color="darkgrey", title.size=0.8, title.position=c("RIGHT","BOTTOM")) #main.title goes above map

```


\pagebreak
Beds, zoomed in on Dakar & St Louis

```{r survey2020-beds-zoom, eval=TRUE, fig.height=4.5, fig.width=7.5, fig.show='hold'}

#bbox for Dhakar
bbox <- st_bbox(c(xmin = -17.7, xmax = -17.1, ymax = 14.9, ymin = 14.5), crs = st_crs(4326))

#bbox for Dhakar region incl St Louis
bbox <- st_bbox(c(xmin = -17.6, xmax = -16, ymax = 16.1, ymin = 14.5), crs = st_crs(4326))

tmap::tm_shape(sfsen_adm0, bbox=bbox) +
    tm_borders("black", lwd = .5) +
    #tm_text("iso_a3", size = "AREA") +
#add NA points, have to do separately because shapeNA doesn't work for size    
tm_shape(sfsen_sur[is.na(sfsen_sur$beds),]) +
  tm_dots(shape=3, size = 0.15, col='grey', border.lwd = 0.2) +    
tm_shape(sfsen_sur) +
    tm_symbols(col = "building", alpha=0.8, size = "beds", size.max=420, 
               scale=3, sizes.legend=c(10,100,400), title.col="") +
tm_add_legend(type="symbol", shape=3, labels = "no bed data", size = 0.5, border.lwd = 0.5, col = "grey") +
    tm_scale_bar(breaks=c(0,20,40), position=c("LEFT", "BOTTOM")) +
    tm_scale_bar(breaks=c(0,50,100), position=c("LEFT", "BOTTOM")) +
    tm_layout(main.title='Bed data collected 2020, Dakar & St Louis', main.title.size=1,
              legend.bg.color=TRUE,
              title="map by @afrimapr", title.color="darkgrey", title.size=0.8, title.position=c("RIGHT","BOTTOM")) #main.title goes above map

```

```{r osmb4-beds-zoom, eval=TRUE, fig.height=4.5, fig.width=7.5, fig.show='hold'}

# healthsites data before
tmap::tm_shape(sfsen_adm0, bbox=bbox) +
    tm_borders("black", lwd = .5) +
    #tm_text("iso_a3", size = "AREA") +
#add NA points, have to do separately because shapeNA doesn't work for size    
tm_shape(sfsen_hs[is.na(sfsen_hs$beds),]) +
  tm_dots(shape=3, size = 0.15, col='grey', border.lwd = 0.2) +    
tm_shape(sfsen_hs) +
    tm_symbols(col = "amenity", alpha=0.8, size = "beds", size.max=420, 
               scale=3, sizes.legend=c(10,100,400), title.col="") +
tm_add_legend(type="symbol", shape=3, labels = "no bed data", size = 0.5, border.lwd = 0.5, col = "grey") +
    tm_scale_bar(breaks=c(0,20,40), position=c("LEFT", "BOTTOM")) +
    tm_layout(main.title='Bed data in OSM before 2020, Dakar & St Louis', main.title.size=1,
              title="map by @afrimapr", title.color="darkgrey", title.size=0.8, title.position=c("RIGHT","BOTTOM")) #main.title goes above map

```

\pagebreak
Doctors

```{r survey2020-doctor-numbers, eval=TRUE, fig.height=4.5, fig.width=7.5, fig.show='hold'}


tmap::tm_shape(sfsen_adm0) +
    tm_borders("black", lwd = .5) +
    #tm_text("iso_a3", size = "AREA") +
#add NA points, have to do separately because shapeNA doesn't work for size    
tm_shape(sfsen_sur[is.na(sfsen_sur[['staff_count:doctors']]),]) +
  tm_dots(shape=3, size = 0.15, col='grey', border.lwd = 0.2) +    
tm_shape(sfsen_sur) +
    tm_symbols(col = "building", alpha=0.8, size = "staff_count:doctors", size.max=120, 
               scale=3, sizes.legend=c(1,10,100), title.col="") +
tm_add_legend(type="symbol", shape=3, labels = "no data", size = 0.5, border.lwd = 0.5, col = "grey") +
    tm_scale_bar(breaks=c(0,50,100), position=c("LEFT", "BOTTOM")) +
    tm_layout(main.title='Doctor number data collected 2020', main.title.size=1,
              legend.bg.color=TRUE,
              title="map by @afrimapr", title.color="darkgrey", title.size=0.8, title.position=c("RIGHT","BOTTOM")) #main.title goes above map

```

Nurses

```{r survey2020-nurse-numbers, eval=TRUE, fig.height=4.5, fig.width=7.5, fig.show='hold'}

tmap::tm_shape(sfsen_adm0) +
    tm_borders("black", lwd = .5) +
    #tm_text("iso_a3", size = "AREA") +
#add NA points, have to do separately because shapeNA doesn't work for size    
tm_shape(sfsen_sur[is.na(sfsen_sur[['staff_count:nurses']]),]) +
  tm_dots(shape=3, size = 0.15, col='grey', border.lwd = 0.2) +    
tm_shape(sfsen_sur) +
    tm_symbols(col = "building", alpha=0.8, size = "staff_count:nurses", size.max=300, 
               scale=3, sizes.legend=c(1,10,100,500), title.col="") +
tm_add_legend(type="symbol", shape=3, labels = "no data", size = 0.5, border.lwd = 0.5, col = "grey") +
    tm_scale_bar(breaks=c(0,50,100), position=c("LEFT", "BOTTOM")) +
    tm_layout(main.title='Nurse number data collected 2020', main.title.size=1,
              title="map by @afrimapr", title.color="darkgrey", title.size=0.8, title.position=c("RIGHT","BOTTOM")) #main.title goes above map

```

\pagebreak
Emergency 

```{r survey2020-emergency-capacity, eval=TRUE, fig.height=4.5, fig.width=7.5, fig.show='hold'}

#todo in tmap can I use repel to stop points being on top of each other

tmap::tm_shape(sfsen_adm0) +
    tm_borders("black", lwd = .5) +
    #tm_text("iso_a3", size = "AREA") +
#add NA points, have to do separately because shapeNA doesn't work for size    
# tm_shape(sfsen_sur[is.na(sfsen_sur[['emergency']]),]) +
#   tm_dots(shape=3, size = 0.15, col='grey', border.lwd = 0.2) +    
tm_shape(sfsen_sur) +
    #decide whether to have shape or colour for emergency
    #todo replace emergency blanks with unknown
    #tm_symbols(shape = "building", alpha=0.6, col = "emergency", scale=1, title.col="") +
    tm_symbols(shape = "building", alpha=0.6, col = "emergency", scale=0.7, title.col="Emergency\ncapacity", palette=c("white","blue","red")) + 
    #tm_add_legend(type="symbol", shape=3, labels = "no data", size = 0.5, border.lwd = 0.5, col = "grey") +  
    tm_scale_bar(breaks=c(0,50,100), position=c("LEFT", "BOTTOM")) +
    tm_layout(main.title='Emergency capacity data collected 2020', main.title.size=1,
              legend.bg.color=TRUE,
              title="map by @afrimapr", title.color="darkgrey", title.size=0.8, title.position=c("RIGHT","BOTTOM")) #main.title goes above map

```



```{r barplot-beds, eval=FALSE, fig.height=5, fig.width=7.5, fig.show='hold'}

#ggplot2::ggplot(sfsen_sur, aes(y = beds, fill = beds)) +
ggplot2::ggplot(sfsen_sur, aes(x = beds, fill = beds)) +
      geom_bar(show.legend=FALSE) +
      theme_minimal() 
      #geom_text(stat='count', aes(label=..count..), hjust='left') + # hjust=-1) +
      #labs(title=plot_title)


```

```{r hospital-services, eval=FALSE, fig.height=4.5, fig.width=7.5, fig.show='hold'}

# 2021-01-12 Mark wants to know

# Of the 35 hospitals mapped X had an emergency serice
# Of the 35 hospitals mapped X had an x-ray and or an imaging serice
# Of the 35 hospitals mapped X had an ultrasound serice
# Of the 35 hospitals mapped X received electricity from the power grid
# Of the 35 hospitals mapped X received water from water works

#str(sfsen_sur)
 # $ name        : chr  "Centre de santé de Rufisque" 
 # $ building            : chr  "Doctors" "Doctors" "Hospital" "Doctors" ...
 # $ health_amenity:type : chr  "Doctor Pharmacy Dentist Laboratory Optometry/Ophtalmology Birthing center" "Doctor Pharmacy Laboratory Rehabilitation Birthing center" "Pharmacy Clinic Alternative Laboratory" "Doctor Pharmacy Dentist Laboratory Birthing center" ...
 # $ healthcare:equipment: chr  "Ultrasound X-Ray Operating Theater Laboratory Imaging Equipment Emergency Department" "Ultrasound X-Ray Laboratory Imaging Equipment Emergency Department" "MRI Laboratory Imaging Equipment Emergency Department" "Laboratory" ...
 # $ emergency           : chr  "Yes" "Yes" "Yes" "No" ...
 # $ insurance:health    : chr  "Public Private" "Public Private" "Private" ...
 # $ staff_count:doctors : int  4 8 4 2 NA 30 NA 2 NA 9 ...
 # $ staff_count:nurses  : int  10 7 22 2 NA 10 NA 3 NA 4 ...
 # $ beds                : int  40 44 16 15 NA 15 NA NA NA 10 ...
 # $ electricity         : chr  "Power grid" "Power grid" "Power grid" "Power grid" ...
 # $ water_source        : chr  "Water works" "Water works" "Water works" "Water works" ...

#select hospitals
# calc percent emergency
dfsen_sur


```

```{r survey2020-hospital-operating-theatre, eval=TRUE, fig.height=4.5, fig.width=7.5, fig.show='hold'}
# 2021-02-12 Mark request
# https://github.com/healthsites/emergency-health-data/wiki#maternity-care
# same style as above but focused on 'operating theatre, Paediatric surgery or ultrasound'..?

#may want to use earlier datafile that I think had services in separate columns

sfsen_sur_hos <- dplyr::filter(sfsen_sur, building=="Hospital")

sfsen_sur_hos <- dplyr::mutate(sfsen_sur_hos, operating = grepl("Operating",`healthcare:equipment`),
                                              icu = grepl("Intensive",`healthcare:equipment`),
                                              ultrasound = grepl("Ultrasound",`healthcare:equipment`))


tmap::tm_shape(sfsen_adm0) +
    tm_borders("black", lwd = .5) +
  
    tm_shape(sfsen_sur_hos) +

    tm_symbols( shape="operating", shapes= c(4,21), alpha=0.6, size=0.5, col='darkgreen', title.shape="Operating\ntheatre") + 
    #tm_add_legend(type="symbol", shape=3, labels = "no data", size = 0.5, border.lwd = 0.5, col = "grey") +  
    #main.title goes above map, title.position: uppercase RIGHT & BOTTOM ignore margins
    tm_scale_bar(breaks=c(0,50,100), position=c("LEFT", "BOTTOM")) +
    tm_layout(main.title='Operating theatre data collected 2020', main.title.size=1,
              title="map by @afrimapr", title.color="darkgrey", title.size=0.8, title.position=c("RIGHT","BOTTOM")) 

```

```{r survey2020-hospital-ultrasound, eval=TRUE, fig.height=4.5, fig.width=7.5, fig.show='hold'}

#using df created in previous chunk

tmap::tm_shape(sfsen_adm0) +
    tm_borders("black", lwd = .5) +
  
    tm_shape(sfsen_sur_hos) +

    tm_symbols( shape="ultrasound", shapes= c(4,21), alpha=0.6, size=0.5, col='darkgreen', title.shape="Ultrasound") + 
    #tm_add_legend(type="symbol", shape=3, labels = "no data", size = 0.5, border.lwd = 0.5, col = "grey") +  
    #main.title goes above map, title.position: uppercase RIGHT & BOTTOM ignore margins
    tm_scale_bar(breaks=c(0,50,100), position=c("LEFT", "BOTTOM")) +
    tm_layout(main.title='Ultrasound data collected 2020', main.title.size=1,
              title="map by @afrimapr", title.color="darkgrey", title.size=0.8, title.position=c("RIGHT","BOTTOM")) 

```

```{r survey2020-hospital-icu, eval=TRUE, fig.height=4.5, fig.width=7.5, fig.show='hold'}

#using df created in previous chunk

tmap::tm_shape(sfsen_adm0) +
    tm_borders("black", lwd = .5) +
  
    tm_shape(sfsen_sur_hos) +

    tm_symbols( shape="icu", shapes= c(4,21), alpha=0.6, size=0.5, col='darkgreen', title.shape="Intensive Care Unit") + 
    #tm_add_legend(type="symbol", shape=3, labels = "no data", size = 0.5, border.lwd = 0.5, col = "grey") +  
    #main.title goes above map, title.position: uppercase RIGHT & BOTTOM ignore margins
    tm_scale_bar(breaks=c(0,50,100), position=c("LEFT", "BOTTOM")) +
    tm_layout(main.title='ICU data collected 2020', main.title.size=1,
              title="map by @afrimapr", title.color="darkgrey", title.size=0.8, title.position=c("RIGHT","BOTTOM")) 

```
