---
title: "senegal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(afrihealthsites)
library(knitr) #for kable
library(dplyr)
library(ggplot2)

```

To compare newly collected data on Senegal health facility locations with that from healthsites.io, WHO. 

Part of HOT microgrant.

November 2020


```{r read-data, eval=TRUE, echo=FALSE, warning=FALSE}


sfsen_who <- afrihealthsites::afrihealthsites('senegal', datasource = 'who', plot = FALSE)

#dfsen_who <- afrihealthsites::afrihealthsites('senegal', datasource = 'who', plot = FALSE, returnclass = 'dataframe')

sfsen_hs <- afrihealthsites::afrihealthsites('senegal', datasource = 'healthsites', plot = FALSE)
# remove pharmacies, dentists & NA
#sfsen_hs <- filter(sfsen_hs, amenity != "pharmacy")
sfsen_hs <- filter(sfsen_hs, amenity %in% c("clinic","doctors","hospital"))
# convert beds to numeric
sfsen_hs$beds <- as.numeric(sfsen_hs$beds) 

#2020-11-Senegal-emergency-health-data_update-osm.xlsx

urldata <- "https://raw.githubusercontent.com/afrimapr/afrimapr_dev/master/data-raw/2020-11-Senegal-emergency-health-data_update-osm.csv"

# read in data
# first versions saved from googlesheets needed to be read in utf8
dfsen_sur <- read.csv(urldata, encoding = 'UTF-8', check.names = FALSE)

#dfuser <- googlesheets4::read_sheet(ss = urldata)
# convert to spatial format
sfsen_sur <- sf::st_as_sf(dfsen_sur, coords = c("longitude", "latitude"), crs = 4326, na.fail=FALSE)
# remove 1 pharmacy from survey data to make map legends clearer
sfsen_sur <- filter(sfsen_sur, building != "Pharmacy")


#mapview::mapview(sfsen_sur, zcol='building')

# Warning message: In do.call(paste, args) :
#   unable to translate '<U+FEFF>name' to native encoding
#TODO fix name of first column

str(sfsen_sur)
 # $ <U+FEFF>name        : chr  "Centre de santé de Rufisque" 
 # $ building            : chr  "Doctors" "Doctors" "Hospital" "Doctors" ...
 # $ addr:full           : chr  "Rue Savers" 
 # $ contact:phone       : num  2.21e+11 NA 2.21e+11 NA NA ...
 # $ operator            : chr  "État du Senegal" 
 # $ operator:type       : chr  "Public" "Public" "Government" "" ...
 # $ operational_status  : chr  "Operational" "Operational" 
 # $ opening_hours       : chr  "24/7 - All day, every day" 
 # $ wheelchair          : chr  "Yes" "Yes" "Yes" "Yes" ...
 # $ health_amenity:type : chr  "Doctor Pharmacy Dentist Laboratory Optometry/Ophtalmology Birthing center" "Doctor Pharmacy Laboratory Rehabilitation Birthing center" "Pharmacy Clinic Alternative Laboratory" "Doctor Pharmacy Dentist Laboratory Birthing center" ...
 # $ healthcare:equipment: chr  "Ultrasound X-Ray Operating Theater Laboratory Imaging Equipment Emergency Department" "Ultrasound X-Ray Laboratory Imaging Equipment Emergency Department" "MRI Laboratory Imaging Equipment Emergency Department" "Laboratory" ...
 # $ emergency           : chr  "Yes" "Yes" "Yes" "No" ...
 # $ insurance:health    : chr  "Public Private" "Public Private" "Private" ...
 # $ staff_count:doctors : int  4 8 4 2 NA 30 NA 2 NA 9 ...
 # $ staff_count:nurses  : int  10 7 22 2 NA 10 NA 3 NA 4 ...
 # $ beds                : int  40 44 16 15 NA 15 NA NA NA 10 ...
 # $ electricity         : chr  "Power grid" "Power grid" "Power grid" "Power grid" ...
 # $ water_source        : chr  "Water works" "Water works" "Water works" "Water works" ...



```

```{r survey-tmap-beds, eval=TRUE, echo=FALSE, warning=FALSE}

library(tmap)
library(afriadmin)

sfsen_adm0 <- afriadmin('senegal',level=0)

#zoom in ?
#log size scale to show smaller num beds



tmap::tm_shape(sfsen_adm0) +
    tm_borders("black", lwd = .5) +
    #tm_text("iso_a3", size = "AREA") +
#add NA points, have to do separately because shapeNA doesn't work for size    
tm_shape(sfsen_sur[is.na(sfsen_sur$beds),]) +
  tm_dots(shape=3, size = 0.15, col='grey', border.lwd = 0.2) +    
tm_shape(sfsen_sur) +
    tm_symbols(col = "building", alpha=0.8, size = "beds", size.max=420, 
               scale=3, sizes.legend=c(10,100,400), title.col="") +
tm_add_legend(type="symbol", shape=3, labels = "no bed data", size = 0.5, border.lwd = 0.5, col = "grey") +
    tm_layout(main.title='Bed data collected 2020') #main.title goes above map

```


```{r osmb4-tmap-beds, eval=TRUE, echo=FALSE, warning=FALSE}

# healthsites data before
tmap::tm_shape(sfsen_adm0) +
    tm_borders("black", lwd = .5) +
    #tm_text("iso_a3", size = "AREA") +
#add NA points, have to do separately because shapeNA doesn't work for size    
tm_shape(sfsen_hs[is.na(sfsen_hs$beds),]) +
  tm_dots(shape=3, size = 0.15, col='grey', border.lwd = 0.2) +    
tm_shape(sfsen_hs) +
    tm_symbols(col = "amenity", alpha=0.8, size = "beds", size.max=420, 
               scale=3, sizes.legend=c(10,100,400), title.col="") +
tm_add_legend(type="symbol", shape=3, labels = "no bed data", size = 0.5, border.lwd = 0.5, col = "grey") +
    tm_layout(main.title='Bed data in OSM before 2020') #main.title goes above map

```

```{r survey-tmap-beds-zoom, eval=TRUE, echo=FALSE, warning=FALSE}

#bbox for Dhakar
bbox <- st_bbox(c(xmin = -17.7, xmax = -17.1, ymax = 14.9, ymin = 14.5), crs = st_crs(4326))

#bbox for Dhakar region incl St Louis
bbox <- st_bbox(c(xmin = -17.6, xmax = -16, ymax = 16.1, ymin = 14.5), crs = st_crs(4326))

tmap::tm_shape(sfsen_adm0, bbox=bbox) +
    tm_borders("black", lwd = .5) +
    #tm_text("iso_a3", size = "AREA") +
#add NA points, have to do separately because shapeNA doesn't work for size    
tm_shape(sfsen_sur[is.na(sfsen_sur$beds),]) +
  tm_dots(shape=3, size = 0.15, col='grey', border.lwd = 0.2) +    
tm_shape(sfsen_sur) +
    tm_symbols(col = "building", alpha=0.8, size = "beds", size.max=420, 
               scale=3, sizes.legend=c(10,100,400), title.col="") +
tm_add_legend(type="symbol", shape=3, labels = "no bed data", size = 0.5, border.lwd = 0.5, col = "grey") +
    tm_layout(main.title='Bed data collected 2020') #main.title goes above map

```

```{r osmb4-tmap-beds-zoom, eval=TRUE, echo=FALSE, warning=FALSE}

# healthsites data before
tmap::tm_shape(sfsen_adm0, bbox=bbox) +
    tm_borders("black", lwd = .5) +
    #tm_text("iso_a3", size = "AREA") +
#add NA points, have to do separately because shapeNA doesn't work for size    
tm_shape(sfsen_hs[is.na(sfsen_hs$beds),]) +
  tm_dots(shape=3, size = 0.15, col='grey', border.lwd = 0.2) +    
tm_shape(sfsen_hs) +
    tm_symbols(col = "amenity", alpha=0.8, size = "beds", size.max=420, 
               scale=3, sizes.legend=c(10,100,400), title.col="") +
tm_add_legend(type="symbol", shape=3, labels = "no bed data", size = 0.5, border.lwd = 0.5, col = "grey") +
    tm_layout(main.title='Bed data in OSM before 2020') #main.title goes above map

```






```{r barplot-beds, eval=TRUE, echo=FALSE, warning=FALSE}

#ggplot2::ggplot(sfsen_sur, aes(y = beds, fill = beds)) +
ggplot2::ggplot(sfsen_sur, aes(x = beds, fill = beds)) +
      geom_bar(show.legend=FALSE) +
      theme_minimal() 
      #geom_text(stat='count', aes(label=..count..), hjust='left') + # hjust=-1) +
      #labs(title=plot_title)


```

