---
title: "join-checklist"
output: html_document
---
  
## Checklist to support joining data to sub-national admin boundaries.

ISSUE :
There are usually difficulties in joining data to admin boundaries due to spelling, capitalisation, accents etc..

afrimapr wants to improve that, particularly for users relatively new to these issues.

Here we start to develop a checklist identifying code steps that users can work through to aid the joining process.

The use-case is that you want to plot data on a map but the data only have names of regions or places. You also can get some spatial data that does have the coordinates of the regions or places. The data are in a spreadsheet type format and the spatial data are in some kind of GIS format.

STEPS

1. read the data into R as a dataframe (dfdata)
1. read in the spatial data to R as a sf object (sfshapes)
1. check that dfdata is a data.frame and sfshapes is a sf object with class(dfdata) and class(sfshapes) 
1. view both objects and identify the columns that contain the information (e.g. place names) you wish to join the data on.
1. use distinct to check the names in the two columns.
1. think about how you want the names to appear on the map, make a note of any changes to the names you would like to make. 
1. use str_c to create a search and str_subset to detect matches and non-matches.
1. use recode to rename the place names so that they match and appear how you wish them to appear on the map. 
1. try initial join dplyr::left_join(), check that the datasets match up by checking the dimensions of the new dataframe.


TODO
[find example data that can go in here that can be super easily used]
[this may be similar to what Laurie is doing]
[maybe country data from gapminder or similar]
[could subset to African countries from naturalearth]
[look at learnr for developing this as an interactive tutorial]




